# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: JiebaTokenizer
##   - name: RegexFeaturizer
#   - name: CountVectorsFeaturizer
##   - name: LanguageModelFeaturizer
##     model_name: "roberta"
#   - name: RegexEntityExtractor
#   - name: DIETClassifier
#     epochs: 100
##   - name: CRFEntityExtractor
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1
#   - name: ResponseSelector
#     epochs: 100
   - name: JiebaTokenizer
   - name: CountVectorsFeaturizer
   - name: RegexEntityExtractor
   - name: DIETClassifier
     epochs: 100
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1
   - name: ResponseSelector
     epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 3
     epochs: 100
   - name: RulePolicy
